version: '3.9'

services:
  nginx:
    image: "nginx:latest"
    restart: always
    hostname: "nginx"
    ports:
      - '80:80'
    volumes:
      - "${NGINX_HOME:-/nginx}/conf.d:/etc/nginx/conf.d"
      - "${NGINX_HOME:-/nginx}/logs:/var/log/nginx"
      - "${NGINX_HOME:-/nginx}/html:/usr/share/nginx/html"
      - "${NGINX_HOME:-/nginx}/config/nginx.conf:/etc/nginx/nginx.conf"
      # - "${CERT_HOME:-/certs}/nginx:/etc/nginx/certs"
      - "/etc/nginx/certs:/etc/nginx/certs"

  # nextcloud 
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    volumes:
      - ${DB_HOME:-/db}/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=${PASSWD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud:
    image: nextcloud
    restart: always
    ports:
      - 8001:80
    links:
      - db
    depends_on:
      - db
    volumes:
      - ${NEXTCLOUD_HOME:-/nextcloud}/html:/var/www/html
      - ${NEXTCLOUD_HOME:-/nextcloud}/apps:/var/www/html/custom_apps
      - ${NEXTCLOUD_HOME:-/nextcloud}/config:/var/www/html/config
      - ${NEXTCLOUD_HOME:-/nextcloud}/data:/var/www/html/data
      - ${NEXTCLOUD_HOME:-/nextcloud}/theme:/var/www/html/themes/<YOUR_CUSTOM_THEME>
    environment:
      - NEXTCLOUD_ADMIN_USER=${USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${PASSWD}
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${PASSWD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_HOST=db

  # frps
  frps:
    image: snowdreamtech/frps
    hostname: "frps"
    restart: always
    expose:
      - 7000
      - 7500
      - 7400
      - 6000
    network_mode: "host"
    volumes:
      - "${FRPS_HOME:-/frps}/frps.ini:/etc/frp/frps.ini"
